<a href="https://colab.research.google.com/github/devssom/data-analysis/blob/main/%EB%94%A5%EB%9F%AC%EB%8B%9D_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

사용할 데이터
- 레모네이드 : https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/lemonade.csv
- 보스턴집값 : https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/boston.csv
- 아이리스 : https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/iris.csv

# 1. 레모네이드 실습

## 1.1 데이터 준비
독립변수와 종속변수를 분리해내는 것

In [3]:
import pandas as pd

path = "https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/lemonade.csv"
lemon = pd.read_csv(path)
lemon

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48
5  25   50

In [4]:
print(lemon.shape)

(6, 2)


In [18]:
x = lemon[['온도']]
y = lemon[['판매량']]

print(x.shape, y.shape)

(6, 1) (6, 1)


In [19]:
x

온도
0  20
1  21
2  22
3  23
4  24
5  25

In [20]:
y

판매량
0   40
1   42
2   44
3   46
4   48
5   50

## 1.2. 모델 준비

In [22]:
import tensorflow as tf

X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

## 1.3. 모델 학습(FIT)시키기

In [27]:
model.fit(x, y, epochs=1000, verbose=0)
model.fit(x, y, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 5ms/step - loss: 4.8699e-04
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 4.8670e-04
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 4.8636e-04
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 4.8606e-04
Epoch 5/10
1/1 [==============================] - 0s 14ms/step - loss: 4.8572e-04
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 4.8534e-04
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 4.8496e-04
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 4.8460e-04
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 4.8432e-04
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 4.8413e-04


##1.4. 모델 이용하기

In [28]:
model.predict([[15]])

array([[30.090715]], dtype=float32)

In [29]:
model.predict(x)

array([[40.038967],
       [42.028618],
       [44.01827 ],
       [46.00792 ],
       [47.99757 ],
       [49.98722 ]], dtype=float32)

In [30]:
model.get_weights()

[array([[1.9896504]], dtype=float32), array([0.24596037], dtype=float32)]

In [33]:
# 판매량 = 1.9896504 * 온도 + 0.24596037

판매량 = 1.9896504 * 22 + 0.24596037
판매량

44.018269169999996

# 2. 보스턴 집값 실습

## 2.1 데이터 준비
독립변수와 종속변수를 분리해내는 것

-> 보스턴 x_input, y_label 만들기 (종속변수: 'medv')

In [12]:
import pandas as pd

path = "https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/boston.csv"
boston = pd.read_csv(path)
boston.head()

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [11]:
print(boston.shape)

(506, 14)


In [34]:
x = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
y = boston[['medv']]

print(x.shape, y.shape)

(506, 13) (506, 1)


In [55]:
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

model.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 14        
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.fit(x, y, epochs=1000, verbose=0)
model.fit(x, y, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 24.3806
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 24.9838
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 24.8298
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 24.9184
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 24.9690
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 24.8909
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 24.3178
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 24.5775
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 24.0519
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 25.0438


In [39]:
model.predict(x[:5])

array([[30.472223],
       [25.318722],
       [31.666788],
       [30.548607],
       [30.127996]], dtype=float32)

In [40]:
model.predict(x[-5:])

array([[26.833881],
       [24.976582],
       [31.016485],
       [29.42258 ],
       [24.877672]], dtype=float32)

In [41]:
model.get_weights()

[array([[-9.10145342e-02],
        [ 5.87902889e-02],
        [-4.18759547e-02],
        [ 2.97760129e+00],
        [ 1.22751486e+00],
        [ 5.02920628e+00],
        [-4.22755443e-03],
        [-9.85246599e-01],
        [ 1.72963232e-01],
        [-9.27913841e-03],
        [-3.02776366e-01],
        [ 1.54567575e-02],
        [-4.87947226e-01]], dtype=float32), array([3.5904973], dtype=float32)]

In [43]:
# medv = -9.10145342e-02 * x1 + 5.87902889e-02 * x2 + -4.18759547e-02 * x3 + 2.97760129e+00 * x4 + 1.22751486e+00 * x5 + 5.02920628e+00 * x6 + -4.22755443e-03 * x7 + -9.85246599e-01 * x8 + 1.72963232e-01 * x9 + -9.27913841e-03 * x10 + -3.02776366e-01 * x11 + 1.54567575e-02 * x12 + -4.87947226e-01 * x13 + 3.5904973

# 3. 아이리스 품종 분류 실습

지금까지의 회귀 모델과 다른 분류 모델

## 3.1 데이터 준비
독립변수와 종속변수를 분리해내는 것

In [65]:
import pandas as pd
# 데이터를 준비합니다. 

path = 'https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/iris.csv'
data = pd.read_csv(path)
data

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭         품종
0     5.1  3.5    1.4   0.2     setosa
1     4.9  3.0    1.4   0.2     setosa
2     4.7  3.2    1.3   0.2     setosa
3     4.6  3.1    1.5   0.2     setosa
4     5.0  3.6    1.4   0.2     setosa
..    ...  ...    ...   ...        ...
145   6.7  3.0    5.2   2.3  virginica
146   6.3  2.5    5.0   1.9  virginica
147   6.5  3.0    5.2   2.0  virginica
148   6.2  3.4    5.4   2.3  virginica
149   5.9  3.0    5.1   1.8  virginica

[150 rows x 5 columns]

In [66]:
print(data.shape)
print(data.columns)
print(data.info())

(150, 5)
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   꽃잎길이    150 non-null    float64
 1   꽃잎폭     150 non-null    float64
 2   꽃받침길이   150 non-null    float64
 3   꽃받침폭    150 non-null    float64
 4   품종      150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [62]:
# 모든 범주형 변수를 원핫인코딩으로 수치형으로 변경해주기

onehot = pd.get_dummies(data)
onehot

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]

In [63]:
# 독립변수와 종속변수 분리해주기

x = onehot[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
y = onehot[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(x.shape, y.shape)

(150, 4) (150, 3)


In [69]:
# 모델을 준비합니다. 
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

model.summary()

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [73]:
model.fit(x, y, epochs=1000, verbose=0)  # verbose가 없으면 한번 학습할 때마다 한 줄씩 출력하게됨
model.fit(x, y, epochs=10) # 위에서 1000번 학습하는 건 안보고 싶지만 그 다음에 10번 학습하는 것만 출력해서 보는 것

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0689 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0690 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0689 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0693 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0688 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0690 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0689 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0687 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0688 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0687 - accuracy: 0.9800


In [76]:
model.predict(x[:5])

array([[9.99999881e-01, 1.56256590e-07, 4.03749702e-17],
       [9.99996662e-01, 3.38422865e-06, 6.03811756e-15],
       [9.99999285e-01, 7.20214643e-07, 7.44424488e-16],
       [9.99993443e-01, 6.60864134e-06, 2.29886656e-14],
       [9.99999881e-01, 1.05089555e-07, 2.46396144e-17]], dtype=float32)

In [79]:
y[-5:]

품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1

In [80]:
model.get_weights()

[array([[  2.143701  ,   0.58377826,  -1.4825209 ],
        [  6.9116473 ,   1.384849  ,  -1.6531408 ],
        [ -8.677012  ,  -1.1374265 ,   2.3782299 ],
        [-10.401354  ,  -3.2837942 ,   3.708508  ]], dtype=float32),
 array([ 3.9953582,  3.64406  , -3.5817835], dtype=float32)]

# 4. 진짜 인공신경망
보스턴 집값 예측 모델로 만들기

In [81]:
import pandas as pd

path = "https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/boston.csv"
boston = pd.read_csv(path)

x = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
y = boston[['medv']]

print(x.shape, y.shape)

(506, 13) (506, 1)


In [87]:
# H를 히든 레이어로 넣어줌. 그리고 Y에 X 대신 H값을 넣어줌

X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(5)(X)  
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

model.summary()

Model: "model_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_11 (InputLayer)        [(None, 13)]              0         
_________________________________________________________________
dense_7 (Dense)              (None, 5)                 70        
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 6         
Total params: 76
Trainable params: 76
Non-trainable params: 0
_________________________________________________________________


In [90]:
# 2000번 돌리니까 loss 값이 26까지 떨어짐

model.fit(x, y, epochs=1000, verbose=0)
model.fit(x, y, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 25.2623
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 26.7107
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 25.6053
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 25.9584
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 25.3978
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 27.3780
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 25.3586
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 27.3952
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 25.4271
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 27.3253


In [98]:
# 맘에 안들어서 히든 레이어를 더 깊게 해줄거야

X = tf.keras.layers.Input(shape=[13])
H1 = tf.keras.layers.Dense(5)(X)
H2 = tf.keras.layers.Dense(4)(H1)
H3 = tf.keras.layers.Dense(2)(H2)  
Y = tf.keras.layers.Dense(1)(H3)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

model.summary()

Model: "model_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_15 (InputLayer)        [(None, 13)]              0         
_________________________________________________________________
dense_21 (Dense)             (None, 5)                 70        
_________________________________________________________________
dense_22 (Dense)             (None, 4)                 24        
_________________________________________________________________
dense_23 (Dense)             (None, 2)                 10        
_________________________________________________________________
dense_24 (Dense)             (None, 1)                 3         
Total params: 107
Trainable params: 107
Non-trainable params: 0
_________________________________________________________________


In [99]:
# 별로 안낮아지네
ㅋㅋㅋㅋmodel.fit(x, y, epochs=1000, verbose=0)
model.fit(x, y, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 27.7738
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 27.3756
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 28.5242
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 28.0960
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 26.2067
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 27.2135
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 28.4260
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 27.8353
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 25.7320
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 26.3031
